### ISSUE TITLE
Error when trying to boot into rmAudio editor when adding Bard Engine to a project

### ISSUE THREAD

**Issue by SolidplasmaStudios** [gl326/bard-audio#1]
This is for the GMS 2 beta (2022.600.0.143) with rollback netcode, which I have not yet used.

When run normally:

ERROR in
action number 1
of Other Event: User Defined 10
for object objAudioEditor:

JSON parse error
 at gml_Object_objAudioEditor_Other_20 (line 3) - var project_data = json_parse(file_read_string(project_file)); //get data from project
############################################################################################
gml_Object_objAudioEditor_Other_20 (line 3)
gml_Object_objAudioEditor_Create_0 (line 81)

When run in Debug Mode:
___________________________________________
############################################################################################
ERROR in
action number 1
of Create Event
for object <undefined>:

global variable name '__project_directory' index (100641) not set before reading it.
 at gml_Script__get_project (line 34) -         if (global.__project_directory == undefined)
############################################################################################
gml_Script__get_project (line 34)
gml_Script_get_project_directory (line 8) -         _get_project();
gml_Script_get_datafiles_directory (line 7) -             global.__project_datafiles = get_project_directory() + "datafiles\\";
gml_Script_bard_audio_data_load (line 5) -         var _path = get_datafiles_directory()+_filename;
gml_GlobalScript_bard_audio_system (line 326) - bard_audio_data_load();

Probably a bug with the new version of game maker, but lemme know if there'd be a workaround. I'd love to prototype my multiplayer rhythm game with the rollback netcode!

**Comment by gl326** [comment]
hey! try running in debug mode. sorry about that

**Comment by SolidplasmaStudios** [comment]
Hey, thanks for the quick response. When trying in debug, I get the second error I posted, there are actually two there. Also upon loading the project, there's an empty object with no referenceID in the rmAudioEditor. I don't know if it's related.

**Comment by SolidplasmaStudios** [comment]
Getting the same errors as above in the non-beta version, Game Maker ver 2.3.589. When I run the extension without merging it with my project in the beta build I used before, I get an empty black screen.

**Comment by gl326** [comment]
hi there, i am posting a new release shortly and as far as i can tell this
error isn't in it. the code errors you show don't make a ton of sense to me
because they don't actually match what is written in the code i am looking
at. so, i guess try the new one out and see how it goes!

**Comment by SolidplasmaStudios** [comment]
Hi, thank you so much for the update! So when I import the engine into my project, and disable the fiie system sandbox, it now launches in debug mode when I make rmAudioEditor the first room, but I still get the first error above when I launch the game regularly. Is this intended behavior?

**Comment by gl326** [comment]
Ah, that I should fix! That said, the audio editor should never ever be
exposed to a player, only devs. Never noticed this because I only let the
game visit that room when in debug mode 😝
